package records

type Record struct {
	Summary       string
	Country       string
	City          string
	State         string
	Shape         string
	CityLatitude  float64
	CityLongitude float64
}

var Records = []Record{
	{
		Summary:       "Gur rirag bppheerq ba gur svany avtug bs fyrrc-njnl pnzc, Nhthfg 22, 1975 ng Endhrggr Ynxr Oblf Pnzc, Endhrggr Ynxr Arj Lbex.\n\n Nyy f",
		Country:       "USA",
		City:          "Raquette Lake",
		State:         "NY",
		Shape:         "circle",
		CityLatitude:  43.8132,
		CityLongitude: -74.652,
	},
	{
		Summary:       "Irel ornhgvshy yvtugf gung neevirq nsgre guhaqrefgbez va Terracbvag, Oebbxyla.",
		Country:       "USA",
		City:          "New York",
		State:         "NY",
		Shape:         "unknown",
		CityLatitude:  40.75256378421113,
		CityLongitude: -73.9844567179912,
	},
	{
		Summary:       "2007 Pvephyne Bowrpg jvgu 3 yvtugf npebff v87 Uvtugjnl va qnlyvtug",
		Country:       "USA",
		City:          "Newburgh",
		State:         "NY",
		Shape:         "circle",
		CityLatitude:  41.533291388400706,
		CityLongitude: -74.04846678383127,
	},
	{
		Summary:       "V fnj gur bowrpg jnf rknpgyl jung n HSB vf glcvpnyyl qrfpevorq nf. Fbzoereb funcrq jvgu ornzvat yvtug haqre",
		Country:       "USA",
		City:          "New York",
		State:         "NY",
		Shape:         "disk",
		CityLatitude:  40.75256378421113,
		CityLongitude: -73.9844567179912,
	},
	{
		Summary:       "Oevtug, tybjvat erq yvtug genafvgvbaf sebz ubire gb pyrnevat gur ubevmba va frpbaqf .",
		Country:       "USA",
		City:          "Hannawa Falls",
		State:         "NY",
		Shape:         "fireball",
		CityLatitude:  44.61228,
		CityLongitude: -74.97103,
	},
	{
		Summary:       "V jrag bhg fvqr ba zl zbgure qrpx gb unir n pvtnerggr.  V unccrarq gb ybbx hc snpvat fbhgujrfg. Gurer jnf n lryybj, nyzbfg fha yvxr pby",
		Country:       "USA",
		City:          "Bayville",
		State:         "NY",
		Shape:         "circle",
		CityLatitude:  40.9058,
		CityLongitude: -73.5561,
	},
	{
		Summary:       "Ubirevat onyy gung jnf abg sebz guvf jbeyq",
		Country:       "USA",
		City:          "Orchard park",
		State:         "NY",
		Shape:         "sphere",
		CityLatitude:  42.7603,
		CityLongitude: -78.754,
	},
	{
		Summary:       "Zlfrys, fba naq sevraq frra na bowrpg nebhaq 50 gb 100 sg sebz hf va gur fxl.  Guvf bowrpg jnf fgngvbanel.  Vg jnf oevtug juvgr ng gur",
		Country:       "USA",
		City:          "Hornell",
		State:         "NY",
		Shape:         "light",
		CityLatitude:  42.3256,
		CityLongitude: -77.65930000000002,
	},
	{
		Summary:       "Gevnatyr/obbzrenat funcrq HSB arne jnfuvatgbaivyyr nern",
		Country:       "USA",
		City:          "Washingtonville",
		State:         "NY",
		Shape:         "other",
		CityLatitude:  41.4259,
		CityLongitude: -74.1617,
	},
	{
		Summary:       "zbivat abegu gb fbhgu fybjyl, benatr tybjvat onyy funcrq, irel oevtug. Cnffrq qverpgyl bireurnq ng ncebk 200sg ab fbhaq. Ghearq evtug n",
		Country:       "USA",
		City:          "Watertown",
		State:         "NY",
		Shape:         "fireball",
		CityLatitude:  43.97630083333333,
		CityLongitude: -75.90908883333333,
	},
	{
		Summary:       "HAXABJA BOWRPG VA GUR FXL",
		Country:       "USA",
		City:          "Belmont",
		State:         "NY",
		Shape:         "unknown",
		CityLatitude:  42.2334,
		CityLongitude: -78.011,
	},
	{
		Summary:       "zbivat abegu gb fbhgu fybjyl, benatr tybjvat onyy funcrq, irel oevtug. Cnffrq qverpgyl bireurnq ng ncebk 200sg ab fbhaq. Ghearq evtug n",
		Country:       "USA",
		City:          "Watertown",
		State:         "NY",
		Shape:         "fireball",
		CityLatitude:  43.97630083333333,
		CityLongitude: -75.90908883333333,
	},
	{
		Summary:       "V abgvpr n fcnpr fuvc ubirevat bire gur gerrf va zl onpxlneq,  jvgu synfuvatyvtugf. Vg frrzrq fgvyy ohg jura V erpbeqrq vg ba zl cubar",
		Country:       "USA",
		City:          "Mexico",
		State:         "NY",
		Shape:         "triangle",
		CityLatitude:  43.4574,
		CityLongitude: -76.2472,
	},
	{
		Summary:       "Fybj zbivat bowrpg jvgu irel oevtug juvgr yvtugf.",
		Country:       "USA",
		City:          "New York",
		State:         "NY",
		Shape:         "sphere",
		CityLatitude:  40.75256378421113,
		CityLongitude: -73.9844567179912,
	},
	{
		Summary:       "Ynepuzbag, Arj Lbex",
		Country:       "USA",
		City:          "Larchmont",
		State:         "NY",
		Shape:         "cigar",
		CityLatitude:  40.9355,
		CityLongitude: -73.7603,
	},
	{
		Summary:       "Ubirevat synfuvat pvephyne yvtugf va gur fxl",
		Country:       "USA",
		City:          "New York",
		State:         "NY",
		Shape:         "circle",
		CityLatitude:  40.75256378421113,
		CityLongitude: -73.9844567179912,
	},
	{
		Summary:       "2 fcurerf pvepyvat naq obhapvat bss bar nabgure nobir pybhqf.  ((AHSBEP Abgr:  Nqiregvfvat yvtugf??  CQ))",
		Country:       "USA",
		City:          "Kingston",
		State:         "NY",
		Shape:         "sphere",
		CityLatitude:  41.96904712041885,
		CityLongitude: -74.06714345549737,
	},
	{
		Summary:       "Fbhgu Rnfg qverpgvba va fxl oyhr, erq, juvgr synfuvat yvtugf ohg va n fgngvbanel cbfvgvba.  V unir frra guvf ahzrebhf gvzrf naq vg qbrf",
		Country:       "USA",
		City:          "Camden",
		State:         "NY",
		Shape:         "unknown",
		CityLatitude:  43.3381,
		CityLongitude: -75.7537,
	},
	{
		Summary:       "Znffvir oynpx “fuvc” zbivat fybjyl nobhg 3K gerr urvtug nobir tebhaq. Oynpx “onggyrfuvc” sybngvat fvyragyl jvgu fbzr yvtugf.",
		Country:       "USA",
		City:          "Brewster",
		State:         "NY",
		Shape:         "unknown",
		CityLatitude:  41.4098,
		CityLongitude: -73.59,
	},
	{
		Summary:       "Tybjvat Terra Beo naq Incbe Genvy bs vg'f cngu",
		Country:       "USA",
		City:          "Buffalo",
		State:         "NY",
		Shape:         "other",
		CityLatitude:  42.90550146611642,
		CityLongitude: -78.85560749348393,
	},
}
