package records

type Record struct {
	Summary       string
	Country       string
	City          string
	State         string
	Shape         string
	CityLatitude  float64
	CityLongitude float64
}

var Records = []Record{
	{
		Summary:       "The event occurred on the final night of sleep-away camp, August 22, 1975 at Raquette Lake Boys Camp, Raquette Lake New York.\n\n All s",
		Country:       "USA",
		City:          "Raquette Lake",
		State:         "NY",
		Shape:         "circle",
		CityLatitude:  43.8132,
		CityLongitude: -74.652,
	},
	{
		Summary:       "Very beautiful lights that arrived after thunderstorm in Greenpoint, Brooklyn.",
		Country:       "USA",
		City:          "New York",
		State:         "NY",
		Shape:         "unknown",
		CityLatitude:  40.75256378421113,
		CityLongitude: -73.9844567179912,
	},
	{
		Summary:       "2007 Circular Object with 3 lights across i87 Hightway in daylight",
		Country:       "USA",
		City:          "Newburgh",
		State:         "NY",
		Shape:         "circle",
		CityLatitude:  41.533291388400706,
		CityLongitude: -74.04846678383127,
	},
	{
		Summary:       "I saw the object was exactly what a UFO is typically described as. Sombrero shaped with beaming light under",
		Country:       "USA",
		City:          "New York",
		State:         "NY",
		Shape:         "disk",
		CityLatitude:  40.75256378421113,
		CityLongitude: -73.9844567179912,
	},
	{
		Summary:       "Bright, glowing red light transitions from hover to clearing the horizon in seconds .",
		Country:       "USA",
		City:          "Hannawa Falls",
		State:         "NY",
		Shape:         "fireball",
		CityLatitude:  44.61228,
		CityLongitude: -74.97103,
	},
	{
		Summary:       "I went out side on my mother deck to have a cigarette.  I happened to look up facing southwest. There was a yellow, almost sun like col",
		Country:       "USA",
		City:          "Bayville",
		State:         "NY",
		Shape:         "circle",
		CityLatitude:  40.9058,
		CityLongitude: -73.5561,
	},
	{
		Summary:       "Hovering ball that was not from this world",
		Country:       "USA",
		City:          "Orchard park",
		State:         "NY",
		Shape:         "sphere",
		CityLatitude:  42.7603,
		CityLongitude: -78.754,
	},
	{
		Summary:       "Myself, son and friend seen an object around 50 to 100 ft from us in the sky.  This object was stationary.  It was bright white at the",
		Country:       "USA",
		City:          "Hornell",
		State:         "NY",
		Shape:         "light",
		CityLatitude:  42.3256,
		CityLongitude: -77.65930000000002,
	},
	{
		Summary:       "Triangle/boomerang shaped UFO near washingtonville area",
		Country:       "USA",
		City:          "Washingtonville",
		State:         "NY",
		Shape:         "other",
		CityLatitude:  41.4259,
		CityLongitude: -74.1617,
	},
	{
		Summary:       "moving north to south slowly, orange glowing ball shaped, very bright. Passed directly overhead at aprox 200ft no sound. Turned right a",
		Country:       "USA",
		City:          "Watertown",
		State:         "NY",
		Shape:         "fireball",
		CityLatitude:  43.97630083333333,
		CityLongitude: -75.90908883333333,
	},
	{
		Summary:       "UNKNOWN OBJECT IN THE SKY",
		Country:       "USA",
		City:          "Belmont",
		State:         "NY",
		Shape:         "unknown",
		CityLatitude:  42.2334,
		CityLongitude: -78.011,
	},
	{
		Summary:       "moving north to south slowly, orange glowing ball shaped, very bright. Passed directly overhead at aprox 200ft no sound. Turned right a",
		Country:       "USA",
		City:          "Watertown",
		State:         "NY",
		Shape:         "fireball",
		CityLatitude:  43.97630083333333,
		CityLongitude: -75.90908883333333,
	},
	{
		Summary:       "I notice a space ship hovering over the trees in my backyard,  with flashinglights. It seemed still but when I recorded it on my phone",
		Country:       "USA",
		City:          "Mexico",
		State:         "NY",
		Shape:         "triangle",
		CityLatitude:  43.4574,
		CityLongitude: -76.2472,
	},
	{
		Summary:       "Slow moving object with very bright white lights.",
		Country:       "USA",
		City:          "New York",
		State:         "NY",
		Shape:         "sphere",
		CityLatitude:  40.75256378421113,
		CityLongitude: -73.9844567179912,
	},
	{
		Summary:       "Larchmont, New York",
		Country:       "USA",
		City:          "Larchmont",
		State:         "NY",
		Shape:         "cigar",
		CityLatitude:  40.9355,
		CityLongitude: -73.7603,
	},
	{
		Summary:       "Hovering flashing circular lights in the sky",
		Country:       "USA",
		City:          "New York",
		State:         "NY",
		Shape:         "circle",
		CityLatitude:  40.75256378421113,
		CityLongitude: -73.9844567179912,
	},
	{
		Summary:       "2 spheres circling and bouncing off one another above clouds.  ((NUFORC Note:  Advertising lights??  PD))",
		Country:       "USA",
		City:          "Kingston",
		State:         "NY",
		Shape:         "sphere",
		CityLatitude:  41.96904712041885,
		CityLongitude: -74.06714345549737,
	},
	{
		Summary:       "South East direction in sky blue, red, white flashing lights but in a stationary position.  I have seen this numerous times and it does",
		Country:       "USA",
		City:          "Camden",
		State:         "NY",
		Shape:         "unknown",
		CityLatitude:  43.3381,
		CityLongitude: -75.7537,
	},
	{
		Summary:       "Massive black “ship” moving slowly about 3X tree height above ground. Black “battleship” floating silently with some lights.",
		Country:       "USA",
		City:          "Brewster",
		State:         "NY",
		Shape:         "unknown",
		CityLatitude:  41.4098,
		CityLongitude: -73.59,
	},
	{
		Summary:       "Glowing Green Orb and Vapor Trail of it's path",
		Country:       "USA",
		City:          "Buffalo",
		State:         "NY",
		Shape:         "other",
		CityLatitude:  42.90550146611642,
		CityLongitude: -78.85560749348393,
	},
}
